#check docker-compose version command to see which version of docker-compose is installed
# version: '3'

#creates data on the host machine, making it easily
#accessible for backup, inspection or use by other containers or applications
volumes:
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/yoonslee/data/wordpress
#       o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /Users/yoonseonlee/data/mariadb
      o: bind

#custom networks to facilitate communication between the containers
networks:
  inception_network:
    name: inception_network

#represents a containerized application or microservice. Dfines the image to use, env, ports to expose,
#volumes to mount, and other related configuration to the service.
services:
  mariadb:
    build: ./requirements/mariadb/
    #use the image from our local repository, not from the Docker Hub
    image: mariadb:yoonslee
    container_name: mariadb_c
    networks:
      - inception_network
    env_file: .env
    volumes:
       - mariadb:/var/lib/mysql
    # tty: true
    restart: always

  # wordpress:
  #   image: wordpress
  #   container_name: wordpress_c
  # #   networks:
  # #       - inception_network
  #   depends_on:
  #     - mariadb
  #   env_file: .env
  # #   volumes:
  # #    - wordpress:/var/www/html
  #   restart: always

  nginx:
    build: ./requirements/nginx/
    image: nginx:yoonslee
    container_name: nginx_c
    ports:
      - "443:443"
    networks:
      - inception_network
    # depends_on:
    #   # - wordpress
    # volumes:
    #   - wordpress:/var/www/html
    restart: always
